// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClH9g3cFoz1onU262KLxqKRCz2SnzzjsM',
    appId: '1:326558222493:android:bc268927a840798b1fac74',
    messagingSenderId: '326558222493',
    projectId: 'food-hub-54593',
    storageBucket: 'food-hub-54593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL6LD2TeXGwZCG8ykGrP4pw-Y8_HmpgA8',
    appId: '1:326558222493:ios:2e01914a04c905ee1fac74',
    messagingSenderId: '326558222493',
    projectId: 'food-hub-54593',
    storageBucket: 'food-hub-54593.appspot.com',
    androidClientId: '326558222493-nio27lijlv1tjmvs0er56cr7e5rvvm5n.apps.googleusercontent.com',
    iosClientId: '326558222493-5ivsef29c09rt4tihci7kgcs65uckbak.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodhub',
  );
}
